name: ✨ Feature request
description: Suggest an idea for RS Kusum Scanner
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem would it solve?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Your idea
      description: How should it work? Sketches and screenshots welcome.
    validations:
      required: true
